notifications:
  email: false
language: node_js
node_js:
- '6'
- '5'
- '4'

before_install:
- npm install forever -g

- git clone https://github.com/Lunik/metrix-master.git
- cd metrix-master
- forever -a start lib/index.js

script:
- npm start
